Series and DataFrames

In [8]:
import pandas as pd
data = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
print(data['c'])

3


In [5]:
'b' in data

True

In [6]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [7]:
list(data.items())

[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]

In [10]:
data['a':'d']

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
data[0:2]

a    1
b    2
dtype: int64

In [22]:
area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})
data1 = pd.DataFrame({'area':area, 'pop':pop})
data1

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [18]:
data1['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [16]:
data1.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [23]:
data1['density'] = data1['pop']/data1['area']
data1

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [25]:
data1.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [27]:
data1.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [28]:
data1.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [30]:
data1.loc[data1.density>100,['area','pop']]

area       pop
New York  141297  19651127
Florida   170312  19552860

Operating on Data (Ufuncs)

In [31]:
import pandas as pd
import numpy as np

In [33]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [34]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [35]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [36]:
np.sin(df * np.pi /4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [38]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127}, name='population')

In [41]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [44]:
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [46]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [49]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),columns=['A','B'])
A

A   B
0   9  15
1  14  14

In [50]:
B = pd.DataFrame(rng.randint(0,18,(3,3)),columns=list('ABC'))
B

A  B   C
0  11  2   4
1   6  8   6
2  17  3  13

In [51]:
A+B

A     B   C
0  20.0  17.0 NaN
1  20.0  22.0 NaN
2   NaN   NaN NaN

In [57]:
fill = A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0  20.0  17.0  17.0
1  20.0  22.0  19.0
2  30.0  16.0  26.0

In [58]:
A = rng.randint(10,size=(3,4))
A

array([[1, 9, 8, 9],
       [4, 1, 3, 6],
       [7, 2, 0, 3]])

In [59]:
A-A[0]

array([[ 0,  0,  0,  0],
       [ 3, -8, -5, -3],
       [ 6, -7, -8, -6]])

In [61]:
df = pd.DataFrame(A,columns=list('QRST'))
print(df)
df - df.iloc[0]
print(df)

   Q  R  S  T
0  1  9  8  9
1  4  1  3  6
2  7  2  0  3
   Q  R  S  T
0  1  9  8  9
1  4  1  3  6
2  7  2  0  3


In [62]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -8  0 -1  0
1  3  0  2  5
2  5  0 -2  1

In [65]:
df.iloc[0,::2]

Q    1
S    8
Name: 0, dtype: int32

Handling missing data

In [68]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [69]:
for dtype in ['object', 'int']:
 print("dtype =", dtype)
 %timeit np.arange(1E6, dtype=dtype).sum()
 print()

dtype = object
161 ms ± 49.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
4.79 ms ± 850 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [71]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [73]:
1+np.nan
0*np.nan

nan

In [74]:
vals2.sum(),vals2.min(),vals2.max()

(nan, nan, nan)

In [75]:
np.nansum(vals2),np.nanmin(vals2),np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [76]:
data = pd.Series([1,np.nan,'hello',None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [77]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [78]:
data.dropna()

0        1
2    hello
dtype: object

In [79]:
df = pd.DataFrame([[1,  np.nan, 2],
                   [2,  3,  5],
                   [np.nan, 4,  6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [80]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [81]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [82]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [83]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [84]:
df.dropna(axis='columns',how='any')

2
0  2
1  5
2  6

In [85]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [87]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [88]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [89]:
data.fillna(method='ffill')

C:\Users\admin\AppData\Local\Temp\ipykernel_17344\1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [90]:
data.fillna(method='bfill')

C:\Users\admin\AppData\Local\Temp\ipykernel_17344\1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [91]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [92]:
df.fillna(method='ffill',axis=1)

C:\Users\admin\AppData\Local\Temp\ipykernel_17344\2272395643.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis=1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

Concatenate and Append

In [93]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
x = [[1,2],[3,4]]
np.concatenate([x,x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [96]:
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
print(ser1)
print()
ser2 = pd.Series(['D','E','F'],index=[4,5,6])
print(ser2)

1    A
2    B
3    C
dtype: object

4    D
5    E
6    F
dtype: object


In [97]:
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object